import type { Metadata } from "next"
import getAllUsers from "@/lib/getAllUsers"
import Link from "next/link"


export const metadata: Metadata = {
    title: "Users List",
    description: 'Generated by create next app',
}


const page = async () => {
  const usersData: Promise<User[]> = getAllUsers()

  const users = await usersData

  return (
    <div className="text-center pt-10">
        <h2 className='text-purple-600 mb-7'>
            <Link href="/">Back To Home</Link>
        </h2>

        {
            users?.map(user => (
                <p key={user.id} className="mb-2">
                    <Link href={`/users/${user.id}`}>{user.name}</Link>
                </p>
            ))
        }
    </div>
  )
}

export default page